import BrowserOnly from "@docusaurus/BrowserOnly";
import Head from "@docusaurus/Head";
import Link from "@docusaurus/Link";
import useDocusaurusContext from "@docusaurus/useDocusaurusContext";
import Heading from "@theme/Heading";
import Layout from "@theme/Layout";
import clsx from "clsx";
import { useEffect, useState } from "react";

import { Playground } from "../components/views/Playground";
import { Supported } from "../components/views/Supported";
import styles from "./index.module.css";

function HomepageHeader() {
  const { siteConfig } = useDocusaurusContext();
  return (
    <header className={clsx("hero hero--primary", styles.heroBanner)}>
      <div className="container">
        <Heading as="h1" className="hero__title mb-0">
          {siteConfig.title}
        </Heading>
        <p className="m-0">
          {"("}GraphQL Plain Text{")"}
        </p>
        <p className="hero__subtitle">{siteConfig.tagline}</p>
        <div className={`${styles.buttons}`}>
          <Link
            className="button button--secondary button--lg"
            to="/docs/getting-started"
          >
            Get Started
          </Link>
        </div>
      </div>
    </header>
  );
}

export default function Home(): JSX.Element {
  const { siteConfig } = useDocusaurusContext();
  const [isWideScreen, setIsWideScreen] = useState(false);

  useEffect(() => {
    const mediaQuery = window.matchMedia("(min-width: 768px)");
    setIsWideScreen(mediaQuery.matches);

    const handler = (e) => setIsWideScreen(e.matches);
    mediaQuery.addListener(handler);
    return () => mediaQuery.removeListener(handler);
  }, []);

  return (
    <Layout
      title={`Home`}
      description="Leverage AI to generate GraphQL queries from plain text"
    >
      <Head>
        <title>{siteConfig.title}</title>
        <meta name="description" content={siteConfig.tagline} />
        <meta
          name="keywords"
          content="graphql, query, translation, ai, artificial, intelligence, openai, translate, autogenerated, chatgpt, text"
        />
        <meta name="twitter:title" content={siteConfig.title} />
        <meta name="twitter:description" content={siteConfig.tagline} />
        <meta property="og:title" content={siteConfig.title} />
        <meta property="og:description" content={siteConfig.tagline} />
        <meta property="og:url" content="https://gqlpt.dev/" />
      </Head>
      <HomepageHeader />
      <main>
        <section className={styles.features}>
          <BrowserOnly>{() => isWideScreen && <Playground />}</BrowserOnly>
          <BrowserOnly>{() => <Supported />}</BrowserOnly>
        </section>
      </main>
    </Layout>
  );
}
