name: Publish to npm

on:
  push:
    tags:
      - "*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-project
      - run: cd ./packages/gqlpt && npm pack
      - run: cd ./packages/gqlpt && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
