name: Test Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
      - name: Test
        run: pnpm test
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
